site_name: "Numerical methods, data science and statistics for physical sciences"
theme: readthedocs
theme_dir: 'readthedocs_custom'
edit_uri: edit/master/docs/
repo_url: https://github.com/phy151-ucb/seljak-phy151-fall-2018
extra:
  logo : img/banner.png
  logo_name : true

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
